services:
  db:
    image: postgres:13.15-bookworm
    restart: always
    mem_limit: 1024m
    cpus: 0.25
    environment:
      POSTGRES_USER: postgres
      # export PGPASSWORD
      POSTGRES_PASSWORD: pigidemo
    volumes:
      - /opt/postgresql-13/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5m
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 5432:5432

 
