services:
  db:
    image: postgres:13.15-bookworm
    restart: always
    mem_limit: 512m
    cpus: 0.25
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: pigidemo      
    volumes:
      - /opt/postgresql-13/data:/var/lib/postgresql/data
      - ./etc/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5m
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - 5432:5432

 
